### ISSUE TITLE
look into way to replace embedded preview image with a full-sized one form dcraw

### ISSUE THREAD

**Issue by catdad** [catdad/raw-viewer#135]

**Comment by catdad** [comment]
using `exiftool` is not supported

```bash
[exiftool] Error: writing jpeg preview for "D:\Workspace\Photography\test-image-error\images - Copy\DNG.dng" is not supported
[exiftool]     at upsertJpeg (D:\Git\raw-viewer\lib\exiftool.js:235:11)
[exiftool]     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by catdad** [comment]
Using `exiftool`, ARW files do not render differently in Windows Photo Viewer even though the file itself is changed, the old image still renders 😔
