### ISSUE TITLE
issues with error handling in analytics

### ISSUE THREAD

**Issue by catdad** [catdad/raw-viewer#248]
```
[analytics] { Error: read ECONNRESET
[analytics]     at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
[exiftool] exif D:\DCIM\100CANON\IMG_1330.CR2: 21.07ms
[exiftool] query meta D:\DCIM\100CANON\IMG_1332.CR2: 16.40ms
[exiftool] exif D:\DCIM\100CANON\IMG_1331.CR2: 20.66ms
[analytics] { Error: read ECONNRESET
[analytics]     at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
[analytics] { Error: read ECONNRESET
[analytics]     at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
[analytics-isomorphic] Error: Object has been destroyed
[analytics-isomorphic]     at WebContents.sendToFrame (C:\Workspace\github\raw-viewer\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:157:15)
[analytics-isomorphic]     at Object

**Comment by catdad** [comment]
These errors are actually being handled, which is why the messages are prefixed. This seems okay.
