### ISSUE TITLE
fix MaxListenersExceededWarning

### ISSUE THREAD

**Issue by catdad** [catdad/raw-viewer#55]
```
(node:15524) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:280:19)
    at Writable.addListener (events.js:297:10)
    at Writable.once (events.js:341:8)
    at Promise (D:\Git\raw-viewer\node_modules\node-exiftool\src\lib.js:110:19)
    at new Promise (<anonymous>)
    at Object.executeCommand (D:\Git\raw-viewer\node_modules\node-exiftool\src\lib.js:106:25)
    at ExiftoolProcess._executeCommand (D:\Git\raw-viewer\node_modules\node-exiftool\src\index.js:133:20)
    at ExiftoolProcess.readMetadata (D:\Git\raw-viewer\node_modules\node-exiftool\src\index.js:150:21)
    at execWithHooks (D:\Git\raw-viewer\lib\exiftool.js:27:30)
    at exec (D:\Git\raw-viewer\lib\exiftool.js:51:10)
(node:15524) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:280:19)
    at Writable.addListener (events.js:297:10)
    at Writable.once (events.js:341:8)
    at Promise (D:\Git\raw-viewer\node_modules\node-exiftool\src\lib.js:117:19)
    at new Promise (<anonymous>)
    at Object.executeCommand (D:\Git\raw-viewer\node_modules\node-exiftool\src\lib.js:113:24)
    at ExiftoolProcess._executeCommand (D:\Git\raw-viewer\node_modules\node-exiftool\src\index.js:133:20)
    at ExiftoolProcess.readMetadata (D:\Git\raw-viewer\node_modules\node-exiftool\src\index.js:150:21)
    at execWithHooks (D:\Git\raw-viewer\lib\exiftool.js:27:30)
    at exec (D:\Git\raw-viewer\lib\exiftool.js:51:10)
```

Put this in the main process (that's where it's coming from):

```javascript
process.on('warning', (w) => {
  console.log(w.stack);
});
```

**Comment by catdad** [comment]
Already fixed.
